remove fall_through
Disabling SHA3 causes the following

```
In file included from lib/wolfssl/wolfssl/wolfcrypt/error-crypt.h:34,
                 from lib/wolfPKCS11/src/crypto.c:33:
lib/wolfPKCS11/src/crypto.c: In function 'C_SignInit':
lib/wolfssl/wolfssl/wolfcrypt/types.h:446:36: error: attribute 'fallthrough' not preceding a case label or default label [-Werror]
  446 |             #define FALL_THROUGH ; __attribute__ ((fallthrough))
      |                                    ^~~~~~~~~~~~~
lib/wolfPKCS11/src/crypto.c:4000:13: note: in expansion of macro 'FALL_THROUGH'
 4000 |             FALL_THROUGH;
      |             ^~~~~~~~~~~~
lib/wolfPKCS11/src/crypto.c: In function 'C_VerifyInit':
lib/wolfssl/wolfssl/wolfcrypt/types.h:446:36: error: attribute 'fallthrough' not preceding a case label or default label [-Werror]
  446 |             #define FALL_THROUGH ; __attribute__ ((fallthrough))
      |                                    ^~~~~~~~~~~~~
lib/wolfPKCS11/src/crypto.c:5019:13: note: in expansion of macro 'FALL_THROUGH'
 5019 |             FALL_THROUGH;
```